name: Update IP Ranges

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "53 */3 * * *" # I'm on a prime schedule - every 3 hours at 53 minutes, because ordinary schedules are just too divisible! :)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Googlebot Script
        run: |
          chmod +x ./googlebot/start.sh
          ./googlebot/start.sh

      - name: Extract Timestamp from File (Googlebot)
        id: extract-timestamp
        run: echo "googlebot_utc=$(<./googlebot/timestamp.txt)" >> "$GITHUB_OUTPUT"

      - name: Git Auto Commit (Googlebot)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[BOT] [Googlebot] changes - ${{ steps.extract-timestamp.outputs.googlebot_utc }}"
          push_options: '--force'

      - name: Run OCI Script
        run: |
          chmod +x ./oracle/start.sh
          ./oracle/start.sh

      - name: Extract Timestamp from File (OCI)
        id: extract-timestamp
        run: echo "oracle_utc=$(<./oracle/timestamp.txt)" >> "$GITHUB_OUTPUT"

      - name: Git Auto Commit (OCI)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[BOT] [OCI] changes - ${{ steps.extract-timestamp.outputs.oracle_utc }}"
          push_options: '--force'
